id = "beancount"
name = "Beancount"
description = "Beancount support."
version = "0.1.0"
schema_version = 1
authors = ["Max Brunsfeld <max@zed.dev>", "Marshall Bowers <marshall@zed.dev>"]
repository = "https://github.com/zed-extensions/beancount"

[grammars.beancount]
repository = "https://github.com/polarmutex/tree-sitter-beancount"
commit = "23b21252da8b8cb0f03d1d1fc4c8f87d407e1cdf"

[language_servers.beancount]
name = "Beancount LSP"
language = "Beancount"
