id = "beancount"
name = "Beancount"
description = "Beancount support."
version = "0.1.0"
schema_version = 1
authors = ["Max Brunsfeld <max@zed.dev>", "Marshall Bowers <marshall@zed.dev>"]
repository = "https://github.com/zed-extensions/beancount"

[grammars.beancount]
repository = "https://github.com/polarmutex/tree-sitter-beancount"
commit = "554e4c9288ad7ad9d66e1adfbd5c531069f61012"

[language_servers.beancount]
name = "Beancount LSP"
language = "Beancount"
